version: '3.8'

services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
      - SOURCE_CODE_SERVICE_URL=http://source-code-service:8000
    depends_on:
      - source-code-service

  source-code-service:
    build:
      context: ./services/source-code-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./services/source-code-service:/app
      - ./data:/data
    environment:
      - LOG_LEVEL=DEBUG
      - CLONE_BASE_PATH=/data/repos
      - FILES_BASE_PATH=/data/files
      - DB_PATH=/data/db
      - ANALYSIS_RESULTS_PATH=/data/analysis
      - CACHE_DIR=/data/cache
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy-key}
      - LLM_PROVIDER=ollama  # or "openai"
      - OLLAMA_API_BASE=http://host.docker.internal:11434
      - OLLAMA_MODEL=mistral:latest

  web-ui:
    build:
      context: ./services/web-ui
      dockerfile: Dockerfile.dev
    ports:
      - "3001:5173"
    volumes:
      - ./services/web-ui:/app
      - /app/node_modules
    command: >
      sh -c "npm install --save-dev ts-node && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080/api/v1/source-code
    depends_on:
      - api-gateway